- server:
    server_name: myserver.com
    port: 8080
    client_max_body_size: 10M
    root: ./public

    error_pages:
        404: /errors/404.html
        500: /errors/500.html
        403: /errors/403.html

    locations:
        - path: /
          methods: GET
          handler: index/index.html
          allow_uploads: false
          content_type: text/html

        - path: /uploadPage
          methods: GET, POST
          handler: index/post.html
          allow_uploads: true

        - path: /upload
          methods: POST
          handler: internal
          allow_uploads: true

        - path: /deletePage
          methods: GET, DELETE
          handler: index/delete.html
          allow_uploads: false
          content_type: text/html

        - path: /file-list
          methods: GET
          handler: internal
          allow_uploads: false

        - path: /files
          methods: DELETE, OPTIONS
          handler: internal
          allow_uploads: false

- server:
    server_name: secondserver.com
    port: 80
    client_max_body_size: 1M
    root: ./public

    error_pages:
        404: /errors/404.html
        500: /errors/500.html

    locations:
        - path: /images
          methods: GET
          handler: images/
          allow_uploads: false
          content_type: image/jpeg

        - path: /videos
          methods: GET
          handler: videos/
          allow_uploads: false
          content_type: video/mp4

        - path: /
          methods: GET
          handler: index/index.html
          allow_uploads: false
          content_type: text/html
